# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-22 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='组名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('corpid', models.CharField(max_length=100, verbose_name='企业ID')),
                ('corpsecret', models.CharField(max_length=100, verbose_name='app密钥')),
                ('agentid', models.CharField(max_length=100, verbose_name='agentID')),
                ('extend1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段1')),
                ('extend2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段2')),
                ('extend3', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段3')),
            ],
            options={
                'db_table': 'group',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_name', models.CharField(max_length=100, verbose_name='日志名称')),
                ('log_info', models.TextField(blank=True, null=True, verbose_name='日志内容')),
                ('extend1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段1')),
                ('extend2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段2')),
                ('extend3', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段3')),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('telephone', models.CharField(max_length=20, verbose_name='手机号')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('extend1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段1')),
                ('extend2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段2')),
                ('extend3', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段3')),
            ],
            options={
                'db_table': 'receptor',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.Group', verbose_name='组外键')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.Receptor', verbose_name='接收人员外键')),
            ],
            options={
                'db_table': 'relation',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=50, verbose_name='策略名称')),
                ('time_quantum', models.CharField(max_length=50, verbose_name='时间段')),
                ('channel', models.IntegerField(choices=[(1, '微信'), (2, '邮箱'), (3, '语音'), (4, '短信')], verbose_name='渠道')),
                ('msg', models.TextField(verbose_name='告知信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('extend1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段1')),
                ('extend2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段2')),
                ('extend3', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段3')),
                ('recept_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', related_query_name='gruop_name', to='strategy.Group', verbose_name='接收组')),
            ],
            options={
                'db_table': 'strategy',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='log',
            name='strategy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='strategy.Strategy', verbose_name='策略外键'),
        ),
    ]
