# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-22 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-id']},
        ),
    ]
