# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-24 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_auto_20181022_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='channel',
            field=models.IntegerField(choices=[set([1, '微信']), set([2, '邮箱']), set(['语音', 3]), set(['短信', 4])], verbose_name='渠道'),
        ),
    ]
