# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-24 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_auto_20181024_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='channel',
            field=models.IntegerField(choices=[(1, '微信'), (2, '邮箱'), (3, '语音'), (4, '短信')], verbose_name='渠道'),
        ),
    ]
